server:
  namespace: key-value
  commonName: server

  # Service
  service:
    type: ClusterIP
    port: 8080

  # Container Image
  container:
    keyValueStorage:
      name: key-value-storage

      image: ikaliuzh/key-value-storage
      imageVersion: v4.0

      # Container Port
      port: 8080

      # Container Resources
      resources:
        limits:
          memory: 512Mi
          cpu: 500m
        requests:
          memory: 256Mi
          cpu: 250m

  # Number of Pod Replicas
  replicas: 1

  # HorizontalPodAutoscaler
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 10
    targetMemoryUtilizationPercentage: 20
